#ifndef OSCILLOGRAPH_GLOBAL_H
#define OSCILLOGRAPH_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(OSCILLOGRAPH_LIBRARY)
#  define OSCILLOGRAPHSHARED_EXPORT Q_DECL_EXPORT
#else
#  define OSCILLOGRAPHSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // OSCILLOGRAPH_GLOBAL_H
